name: Change
description: Change/improvement suggestion

body:

  - type: markdown
    attributes:
      value: "> _This template is rather extensive. Fill out all that you can, if are a new contributor or you're unsure about any section, leave it unchanged and a reviewer will help you_ :smile:."

  - type: textarea
    validations:
      required: true
    attributes:
      label: Expected behavior
      description: Tell us how it should work

  - type: textarea
    validations:
      required: true
    attributes:
      label: Current behavior
      description: Explain the difference from current behavior

  - type: textarea
    validations:
      required: true
    attributes:
      label: Possible implementation
      description: Suggest ideas how to implement the addition or change

  - type: textarea
    attributes:
      label: Context
      description: How has this issue affected you? What are you trying to accomplish? Providing context helps us come up with a solution that is most useful in the real world.

  - type: input
    attributes:
      label: Link to your project
